export const partnerList = [{
    partner: "Partner1",
    name: "Partner 1",
    partnerId: 1
}, {
    partner: "Partner2",
    name: "Partner 2",
    partnerId: 2,
}, {
    partner: "Partner3",
    name: "Partner 3",
    partnerId: 3,
}, {
    partner: "Partner1",
    name: "Partner 4",
    partnerId: 4,
}, {
    partner: "Partner2",
    name: "Partner 5",
    partnerId: 5,
}, {
    partner: "Partner3",
    name: "Partner 6",
    partnerId: 6,
}];

export const productDump = [{
    "itemId": "1",
    "name": "Bespoke Fresh Chair",
    "price": "202.00",
    "inStock": "2",
    "fastDelivery": true,
    "ratings": "8",
    "partnerId": "2",
    "size": "L",
    "quantity": "64",
    "sku": "7c405270-7db8-468c-951e-d4d72c3da0fc",
    "partner": "Partner2",
    "category": "Eyewear",
    "description": "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    "color": "Yellow"
}, {
    "itemId": "2",
    "name": "Handcrafted Frozen Shirt",
    "price": "6.00",
    "inStock": "7",
    "fastDelivery": false,
    "ratings": "4",
    "partnerId": "1",
    "size": "M",
    "quantity": "71",
    "sku": "e073ae31-dc4b-4a3a-b1a2-f050db3949e9",
    "partner": "Partner1",
    "category": "Apparel",
    "description": "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    "color": "Yellow"
}, {
    "itemId": "3",
    "name": "Luxurious Cotton Mouse",
    "price": "47.00",
    "inStock": "6",
    "fastDelivery": true,
    "ratings": "1",
    "partnerId": "1",
    "size": "L",
    "quantity": "32",
    "sku": "d0b1d553-a9ae-42c3-869d-ff6aee49650e",
    "partner": "Partner1",
    "category": "Footware",
    "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    "color": "Yellow"
}, {
    "itemId": "4",
    "name": "Handcrafted Bronze Pants",
    "price": "192.00",
    "inStock": "8",
    "fastDelivery": true,
    "ratings": "8",
    "partnerId": "1",
    "size": "L",
    "quantity": "64",
    "sku": "92ddb729-8f83-4a9a-9cc8-87d54c75cd6a",
    "partner": "Partner1",
    "category": "Eyewear",
    "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "color": "Red"
}, {
    "itemId": "5",
    "name": "Gorgeous Frozen Chair",
    "price": "240.00",
    "inStock": "4",
    "fastDelivery": true,
    "ratings": "4",
    "partnerId": "2",
    "size": "L",
    "quantity": "78",
    "sku": "5b87d907-f40c-4e82-93aa-b6dcda8ae875",
    "partner": "Partner2",
    "category": "Apparel",
    "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    "color": "Red"
}, {
    "itemId": "6",
    "name": "Elegant Granite Chips",
    "price": "368.00",
    "inStock": "1",
    "fastDelivery": true,
    "ratings": "2",
    "partnerId": "2",
    "size": "S",
    "quantity": "20",
    "sku": "73f923d6-b807-46f2-8f96-214e8f106ef7",
    "partner": "Partner2",
    "category": "Footware",
    "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    "color": "Green"
}, {
    "itemId": "7",
    "name": "Elegant Metal Fish",
    "price": "31.00",
    "inStock": "7",
    "fastDelivery": true,
    "ratings": "3",
    "partnerId": "1",
    "size": "L",
    "quantity": "69",
    "sku": "a1c57401-5836-4e2e-b9dc-9352c3102c14",
    "partner": "Partner1",
    "category": "Apparel",
    "description": "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    "color": "Red"
}, {
    "itemId": "8",
    "name": "Sleek Concrete Pizza",
    "price": "922.00",
    "inStock": "2",
    "fastDelivery": true,
    "ratings": "3",
    "partnerId": "3",
    "size": "M",
    "quantity": "44",
    "sku": "d35ffb6e-d923-4dab-b2a4-be07ef094644",
    "partner": "Partner3",
    "category": "Footware",
    "description": "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
    "color": "Yellow"
}, {
    "itemId": "9",
    "name": "Oriental Concrete Soap",
    "price": "71.00",
    "inStock": "1",
    "fastDelivery": true,
    "ratings": "7",
    "partnerId": "2",
    "size": "S",
    "quantity": "87",
    "sku": "ddf29cfe-a536-48d7-98ff-bd9270ed4b0d",
    "partner": "Partner2",
    "category": "Apparel",
    "description": "The Football Is Good For Training And Recreational Purposes",
    "color": "Yellow"
}, {
    "itemId": "10",
    "name": "Recycled Metal Bacon",
    "price": "608.00",
    "inStock": "1",
    "fastDelivery": false,
    "ratings": "2",
    "partnerId": "2",
    "size": "S",
    "quantity": "84",
    "sku": "434eab8f-ac06-4201-ad54-81717558c4a5",
    "partner": "Partner2",
    "category": "Footware",
    "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "color": "Red"
}, {
    "itemId": "11",
    "name": "Handcrafted Steel Tuna",
    "price": "651.00",
    "inStock": "4",
    "fastDelivery": true,
    "ratings": "4",
    "partnerId": "3",
    "size": "L",
    "quantity": "38",
    "sku": "994aa035-8c03-4e4c-b57d-f34f22b2ea38",
    "partner": "Partner3",
    "category": "Apparel",
    "description": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    "color": "Yellow"
}, {
    "itemId": "12",
    "name": "Generic Frozen Car",
    "price": "514.00",
    "inStock": "8",
    "fastDelivery": true,
    "ratings": "6",
    "partnerId": "3",
    "size": "L",
    "quantity": "40",
    "sku": "16546359-7c1d-4491-99a7-ce23eb7e7fa6",
    "partner": "Partner3",
    "category": "Footware",
    "description": "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
    "color": "Yellow"
}, {
    "itemId": "13",
    "name": "Modern Cotton Cheese",
    "price": "936.00",
    "inStock": "9",
    "fastDelivery": false,
    "ratings": "7",
    "partnerId": "3",
    "size": "L",
    "quantity": "30",
    "sku": "d88ab003-2732-463b-8fdb-003ea676b9a9",
    "partner": "Partner3",
    "category": "Apparel",
    "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "color": "Yellow"
}, {
    "itemId": "14",
    "name": "Small Fresh Pizza",
    "price": "829.00",
    "inStock": "4",
    "fastDelivery": false,
    "ratings": "1",
    "partnerId": "2",
    "size": "S",
    "quantity": "75",
    "sku": "61c0e4cf-74e5-4d6a-b5f6-93708f02f26d",
    "partner": "Partner2",
    "category": "Eyewear",
    "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    "color": "Yellow"
}, {
    "itemId": "15",
    "name": "Elegant Granite Bacon",
    "price": "594.00",
    "inStock": "1",
    "fastDelivery": true,
    "ratings": "9",
    "partnerId": "1",
    "size": "L",
    "quantity": "20",
    "sku": "bf49c6e1-d9d6-4e15-97e8-df5a7bacf97b",
    "partner": "Partner1",
    "category": "Footware",
    "description": "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    "color": "Green"
}, {
    "itemId": "16",
    "name": "Licensed Concrete Keyboard",
    "price": "682.00",
    "inStock": "1",
    "fastDelivery": false,
    "ratings": "6",
    "partnerId": "2",
    "size": "L",
    "quantity": "92",
    "sku": "c9bfc4ee-e840-4a53-b65e-5c6fcbfc8199",
    "partner": "Partner2",
    "category": "Apparel",
    "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    "color": "Yellow"
}, {
    "itemId": "17",
    "name": "Generic Soft Tuna",
    "price": "245.00",
    "inStock": "4",
    "fastDelivery": true,
    "ratings": "2",
    "partnerId": "3",
    "size": "S",
    "quantity": "19",
    "sku": "249ebf72-454d-41bc-ab0f-2a089585e983",
    "partner": "Partner3",
    "category": "Apparel",
    "description": "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    "color": "Yellow"
}, {
    "itemId": "18",
    "name": "Luxurious Granite Mouse",
    "price": "13.00",
    "inStock": "1",
    "fastDelivery": true,
    "ratings": "9",
    "partnerId": "1",
    "size": "S",
    "quantity": "41",
    "sku": "9094570d-7852-44f6-8fe6-0333d92d629c",
    "partner": "Partner1",
    "category": "Eyewear",
    "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "color": "Green"
}, {
    "itemId": "19",
    "name": "Generic Metal Pants",
    "price": "350.00",
    "inStock": "3",
    "fastDelivery": false,
    "ratings": "6",
    "partnerId": "1",
    "size": "S",
    "quantity": "80",
    "sku": "b5fa08f3-23c1-4117-b7f7-af868ebd9991",
    "partner": "Partner1",
    "category": "Footware",
    "description": "The Football Is Good For Training And Recreational Purposes",
    "color": "Green"
}, {
    "itemId": "20",
    "name": "Ergonomic Bronze Pants",
    "price": "278.00",
    "inStock": "5",
    "fastDelivery": false,
    "ratings": "4",
    "partnerId": "3",
    "size": "M",
    "quantity": "77",
    "sku": "66ac5f9d-46da-4bdc-a8f7-fdacb9278a55",
    "partner": "Partner3",
    "category": "Eyewear",
    "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    "color": "Green"
}, {
    "itemId": "21",
    "name": "Rustic Metal Table",
    "price": "731.00",
    "inStock": "3",
    "fastDelivery": false,
    "ratings": "9",
    "partnerId": "2",
    "size": "M",
    "quantity": "96",
    "sku": "a076df61-7a29-450b-9fd9-1e2267009275",
    "partner": "Partner2",
    "category": "Footware",
    "description": "The Football Is Good For Training And Recreational Purposes",
    "color": "Red"
}, {
    "itemId": "22",
    "name": "Recycled Bronze Gloves",
    "price": "366.00",
    "inStock": "2",
    "fastDelivery": false,
    "ratings": "7",
    "partnerId": "1",
    "size": "M",
    "quantity": "20",
    "sku": "4671e2e2-b7c3-44fc-a5e9-10f3ee36380e",
    "partner": "Partner1",
    "category": "Eyewear",
    "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    "color": "Yellow"
}, {
    "itemId": "23",
    "name": "Elegant Rubber Shoes",
    "price": "772.00",
    "inStock": "5",
    "fastDelivery": false,
    "ratings": "5",
    "partnerId": "2",
    "size": "M",
    "quantity": "92",
    "sku": "0a135915-7355-45d3-b7a4-5b33ae4d9b19",
    "partner": "Partner2",
    "category": "Footware",
    "description": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    "color": "Yellow"
}, {
    "itemId": "24",
    "name": "Unbranded Plastic Table",
    "price": "622.00",
    "inStock": "4",
    "fastDelivery": true,
    "ratings": "6",
    "partnerId": "3",
    "size": "L",
    "quantity": "86",
    "sku": "a129a79d-72aa-40e1-aa8c-4223fe0f3217",
    "partner": "Partner3",
    "category": "Eyewear",
    "description": "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
    "color": "Yellow"
}, {
    "itemId": "25",
    "name": "Refined Cotton Table",
    "price": "717.00",
    "inStock": "7",
    "fastDelivery": false,
    "ratings": "7",
    "partnerId": "1",
    "size": "L",
    "quantity": "79",
    "sku": "6b79f174-c075-48e4-9d8f-b9b48ab255a6",
    "partner": "Partner1",
    "category": "Apparel",
    "description": "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    "color": "Green"
}]